### ISSUE TITLE
[1.16.4] Blacklist

### ISSUE THREAD

**Issue by nanohard** [Tofpu/MobPreventer#2]
**Mincecraft 1.16.4 using Paper**
**MobPreventer 1.0.7** (1.0.8 not available for download, though maybe just the jar wasn't renamed for the version bump? downloaded via Spigot)

Confirmed that whitelist works, but blacklist prevents all blocks and entities (NPCs) from dropping anything.

**Comment by Tofpu** [comment]
Hey, sorry about the late response. I had to upgrade my SDD.

Regarding your issue, MobPreventer shouldn't prevent entities from dropping items; are you sure It's from MobPreventer? If possible, list your plugins here.

MobPreventer only listens for:
-  **EntitySpawnEvent** (Triggered when an entity spawns)
-  **SpawnerSpawnEvent** (Triggered when a mob spawns from a spawner)

I'm certain MobPreventer isn't the one causing the issue, but I'm looking forward to your response.

**Comment by nanohard** [comment]
`EntitySpawnEvent` is the parent class of `SpawnerSpawnEvent`, and Items are Entities.
Shouldn't it be `CreatureSpawnEvent` being used? You'd only need one listener, I think, unless both `CreatureSpawnEvent` and `SpawnerSpawnEvent` are needed, ie: `CreatureSpawnEvent` not triggering for Spawner spawned creatures. The way you have it currently it listens for all spawn events: `CreatureSpawnEvent, ItemSpawnEvent, ProjectileLaunchEvent, SpawnerSpawnEvent` and then a second time for `SpawnerSpawnEvent`.

EDIT:
I have also confirmed that it is this plugin that gave me the issue. Ran local server w/ this being the only plugin installed.

EDIT 2:
The entity is question is `DROPPED_ITEM`, or the way you parse it, `droppeditem` (removal of underscore, case-insensitive).
There are other entities affected by this as well that are not creatures.

**Comment by Tofpu** [comment]
> `EntitySpawnEvent` is the parent class of `SpawnerSpawnEvent`, and Items are Entities.
> Shouldn't it be `CreatureSpawnEvent` being used? You'd only need one listener, I think, unless both `CreatureSpawnEvent` and `SpawnerSpawnEvent` are needed, ie: `CreatureSpawnEvent` not triggering for Spawner spawned creatures. The way you have it currently it listens for all spawn events: `CreatureSpawnEvent, ItemSpawnEvent, ProjectileLaunchEvent, SpawnerSpawnEvent` and then a second time for `SpawnerSpawnEvent`.
> 
> EDIT:
> I have also confirmed that it is this plugin that gave me the issue. Ran local server w/ this being the only plugin installed.
> 
> EDIT 2:
> The entity is question is `DROPPED_ITEM`, or the way you parse it, `droppeditem` (removal of underscore, case-insensitive).
> There are other entities affected by this as well that are not creatures.

Ah, I forgot Items are considered as entities and the same thing with the parent classes, working on it as we speak, appreciate it!

**Comment by Tofpu** [comment]
I'll be closing this for now but If it's still somehow not fixed, feel free to reopen it
