### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by Durjam** [Tofpu/MobPreventer#4]
![Captureefwsfweg](https://user-images.githubusercontent.com/68571708/117399020-6a8e7780-aeb4-11eb-8a4d-b981b32aff38.PNG)

**Comment by Tofpu** [comment]
I'd have never seen this if I didn't click on a github link by accident... I advise you for future reference to report/question like this on our discord support server for faster respond time.

Anyway, now that's out of the way!
1) Have you by any chance ran /mobpreventer reload or restarted the server?

2) Were there any errors in startup or upon executing "/mobpreventer reload" in the console?

3) What software & version were you in? Example: Paper, 1.16.4 and Build 432
